version: '3.8'

x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: 'HighSeas - A Netflix-style streaming interface for Stremio addons with Real-Debrid integration. Features HLS transcoding for MKV files, advanced subtitle support, and mobile-optimized controls.'
  tagline:
    en_us: Premium streaming interface for Stremio
  developer: HighSeas
  author: HighSeas Team
  category: Media
  port_map: '6969'
  icon: https://raw.githubusercontent.com/highseas-dev/highseas/main/assets/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/highseas-dev/highseas/main/assets/screenshot1.png
    - https://raw.githubusercontent.com/highseas-dev/highseas/main/assets/screenshot2.png
  thumbnail: https://raw.githubusercontent.com/highseas-dev/highseas/main/assets/thumbnail.png
  title:
    en_us: HighSeas
  tips:
    before_install:
      en_us: |
        ⚠️ **Real-Debrid API Token Required**

        This application requires a Real-Debrid premium account and API token to function properly.

        1. Sign up for a Real-Debrid account at https://real-debrid.com
        2. Go to https://real-debrid.com/apitoken to generate your API token  
        3. Enter the token in the environment variables section during installation

        **Features:**
        - Netflix-style streaming interface
        - Real-Debrid integration for premium streaming
        - HLS transcoding for MKV file support (requires FFmpeg)
        - Advanced subtitle support with SRT/WebVTT parsing
        - Mobile-optimized touch controls
        - Android TV compatibility
        - Pure streaming architecture (no downloads)
  index: /
  scheme: http
  hostname: ''
  image: highseas/highseas:latest

services:
  app:
    image: highseas/highseas:latest
    container_name: highseas
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
      - BODY_SIZE_LIMIT=10mb
      - LOG_LEVEL=info
      - REAL_DEBRID_TOKEN=${REAL_DEBRID_TOKEN:-}
      - ENABLE_AMD_GPU=${ENABLE_AMD_GPU:-true}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    devices:
      - /dev/dri:/dev/dri  # AMD GPU device access for VAAPI transcoding
    group_add:
      - video  # Add container to video group for GPU access
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:6969/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      # CasaOS labels
      - "casaos.name=HighSeas"
      - "casaos.category=Media"
      - "casaos.description=Netflix-style streaming interface for Stremio"
      - "casaos.icon=https://raw.githubusercontent.com/highseas-dev/highseas/main/assets/icon.png"
      - "casaos.main=true"
      # Traefik labels (if using reverse proxy)
      - "traefik.enable=true"
      - "traefik.http.routers.highseas.rule=Host(\`highseas.local\`)"
      - "traefik.http.services.highseas.loadbalancer.server.port=6969"
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  default:
    name: highseas-network
    driver: bridge
