version: '3.8'

services:
  highseas:
    image: caullen/highseas-streaming:latest
    container_name: highseas-streaming
    ports:
      - '6969:6969'
    environment:
      - NODE_ENV=production
      - PORT=6969
      - BODY_SIZE_LIMIT=0
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:6969/api/health || exit 1'
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Optional: Add logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
