# Docker Compose file for GitHub-based builds

# GitHub-based Build Docker Compose
# Builds directly from source code instead of using pre-built images

services:
  highseas-streaming:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - BUILD_DATE=${BUILD_DATE:-unknown}
        - VCS_REF=${VCS_REF:-unknown}
        - VERSION=${VERSION:-latest}
    image: localhost/highseas-streaming:github-production
    container_name: highseas-github-production
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
      - BODY_SIZE_LIMIT=10mb
      - LOG_LEVEL=info
      - LOGS_DIR=/app/logs
      - REAL_DEBRID_TOKEN=${REAL_DEBRID_TOKEN:-}
      - ENABLE_AMD_GPU=${ENABLE_AMD_GPU:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://localhost:6969,http://localhost:4173}
    volumes:
      - highseas-logs:/app/logs
      - /dev/dri:/dev/dri  # AMD GPU access for VAAPI
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # AMD GPU device
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6969/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - highseas-network
    labels:
      - "com.highseas.description=HighSeas Premium Streaming Server"
      - "com.highseas.version=${VERSION:-latest}"
      - "com.highseas.build-date=${BUILD_DATE:-unknown}"
      - "com.highseas.vcs-ref=${VCS_REF:-unknown}"
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'

volumes:
  highseas-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/highseas-logs

networks:
  highseas-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16