version: '3.8'

services:
  highseas-streaming:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/highseas-streaming:github-build
    container_name: highseas-github-build
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
      - BODY_SIZE_LIMIT=10mb
      - LOG_LEVEL=info
      - LOGS_DIR=/app/logs
      - REAL_DEBRID_TOKEN=
      - ENABLE_AMD_GPU=true
    volumes:
      - /tmp/highseas-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6969/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: highseas-network