version: '3.8'

x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: 'HighSeas - A Netflix-style streaming interface for Stremio addons with Real-Debrid integration. Features HLS transcoding for MKV files, advanced subtitle support, and mobile-optimized controls.'
  tagline:
    en_us: Premium streaming interface for Stremio
  developer: HighSeas Team
  author: HighSeas Team
  category: Media
  port_map: '6969'
  icon: https://raw.githubusercontent.com/CaullenOmdahl/HighSeas/master/assets/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/CaullenOmdahl/HighSeas/master/assets/screenshot1.png
    - https://raw.githubusercontent.com/CaullenOmdahl/HighSeas/master/assets/screenshot2.png
  thumbnail: https://raw.githubusercontent.com/CaullenOmdahl/HighSeas/master/assets/thumbnail.png
  title:
    en_us: HighSeas
  tips:
    before_install:
      en_us: |
        ⚠️ **Real-Debrid API Token Required**

        This application requires a Real-Debrid premium account and API token to function properly.

        1. Sign up for a Real-Debrid account at https://real-debrid.com
        2. Go to https://real-debrid.com/apitoken to generate your API token  
        3. Enter the token in the environment variables section during installation

        **Features:**
        - Netflix-style streaming interface
        - Real-Debrid integration for premium streaming
        - FFmpeg HLS transcoding for HEVC/MKV files with AMD GPU acceleration
        - Advanced subtitle support with SRT/WebVTT parsing
        - Mobile-optimized touch controls
        - Android TV compatibility
        - Pure streaming architecture (no downloads)
    after_install:
      en_us: |
        ✅ **HighSeas Installation Complete**
        
        1. Access your HighSeas interface at: http://your-casaos-ip:6969
        2. The application will prompt you if Real-Debrid token is missing
        3. Configure Stremio addons in Settings > Addons
        4. Browse and stream content from the main dashboard
        
        **Viewing Logs:**
        - Application logs: /DATA/AppData/highseas-streaming/logs/
        - Docker logs: `docker logs highseas-streaming`
        - Real-time logs: `docker logs -f highseas-streaming`
        
        **Troubleshooting:**
        - Check logs if Real-Debrid integration fails
        - Ensure FFmpeg is working for HEVC/MKV transcoding
        - Verify network connectivity for streaming
  index: /
  scheme: http
  hostname: ''
  store_app_id: highseas-streaming
  project_url: https://github.com/CaullenOmdahl/HighSeas
  version: "1.2.2"
  envs:
    - container: REAL_DEBRID_TOKEN
      description: 
        en_us: Real-Debrid API Token (Required) - Get from https://real-debrid.com/apitoken
      default: ""
    - container: NODE_ENV
      description:
        en_us: Application environment
      default: production
    - container: PORT
      description:
        en_us: Server port
      default: "6969"
    - container: BODY_SIZE_LIMIT
      description:
        en_us: Request body size limit
      default: "10mb"
    - container: LOG_LEVEL
      description:
        en_us: Logging level (error, warn, info, debug)
      default: info
    - container: ENABLE_AMD_GPU
      description:
        en_us: Enable AMD GPU transcoding (VAAPI)
      default: "true"
    - container: LOGS_DIR
      description:
        en_us: Directory for application logs
      default: "/app/logs"
    - container: CORS_ORIGINS
      description:
        en_us: CORS allowed origins (optional)
      default: ""
  volumes:
    - container: /app/data
      description:
        en_us: Application data directory
    - container: /app/logs
      description:
        en_us: Application logs directory
  ports:
    - container: "6969"
      description:
        en_us: Web interface port

services:
  app:
    image: ghcr.io/caullenomdahl/highseas:latest
    container_name: highseas-streaming
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      NODE_ENV: production
      PORT: 6969
      BODY_SIZE_LIMIT: 10mb
      LOG_LEVEL: info
      LOGS_DIR: /app/logs
      REAL_DEBRID_TOKEN: ${REAL_DEBRID_TOKEN:-}
      ENABLE_AMD_GPU: ${ENABLE_AMD_GPU:-true}
      CORS_ORIGINS: ${CORS_ORIGINS:-}
    volumes:
      - /DATA/AppData/highseas-streaming/data:/app/data
      - /DATA/AppData/highseas-streaming/logs:/app/logs
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - video
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6969/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "casaos.name=HighSeas"
      - "casaos.category=Media"
      - "casaos.description=Netflix-style streaming interface for Stremio"
      - "casaos.icon=https://raw.githubusercontent.com/CaullenOmdahl/HighSeas/master/assets/icon.png"
      - "casaos.main=true"
      - "casaos.index=/"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

networks:
  default:
    name: highseas-network
